### PR TITLE
Some more argument tests

### LINKED ISSUE #119: Too many arguments
The duplicatedArguments Test doesn't check the cases with more than 3 arguments...

### PR DESCRIPTION
**Pull request by RomanLangrehr**
- Fixes #119 
- Removed the (not yet) existing Test classes MoveTest and PrintTest
- Added a few more not well-formed arguments test

### CODE REVIEW

**Comment by pcworld** [comment]
Your formatting is wrong and you broke the formatting of existing code. Please import the new formatter profile.
(Edit: Preferably rebase as not to clutter the history with even more formatting commits.)

**Comment by RomanLangrehr** [comment]
Oh, I'm sorry for that, I'll fix this soon...

**Comment by RomanLangrehr** [comment]
Fixed...

**Comment by pcworld** [comment]
Do you use Eclipse? The formatter file has a 120 maximum line length rule.
Except for the formatting, lgtm.

**Comment by RomanLangrehr** [comment]
Yes, I use eclipse and I'm pretty sure everything is now formatted correctly. I use the formatter from the repository and formatted the whole file.
As you can see in tooManyArgumentsTest, all lines are broken correctly, to match the 120 maximum line length rule.
The line "\t\terrorTest("quit", Input.getFile(TASK_SHEET_INPUT_FILE_1), "rule=270-90-9999999999999999999999999999999999999-45-90");" was not formatted correctly before: The line length is 119!

**Comment by RomanLangrehr** [comment]
And the line "\t     \* Asserts that the tested class prints an error message if a non-existent file is provided as command line argument." has 118 chars, so it should be only one line, too.

**Comment by pcworld** [comment]
My version of Eclipse (3.8.1; or its setup) counts tab characters as four characters (which does make sense, since that's the tab width set up in the formatter profile), thus it always wants to wrap these lines:

``` diff
diff --git a/src/final2/subtests/InvalidCommandLineArgumentsTest.java b/src/final2/subtests/InvalidCommandLineArgumentsTest.java
index 09640a8..2dec9be 100644
--- a/src/final2/subtests/InvalidCommandLineArgumentsTest.java
+++ b/src/final2/subtests/InvalidCommandLineArgumentsTest.java
@@ -100,7 +100,8 @@ public class InvalidCommandLineArgumentsTest extends LangtonSubtest {
        errorTest("quit", Input.getFile(TASK_SHEET_INPUT_FILE_1), "rule=270-0-315-45-90");
        errorTest("quit", Input.getFile(TASK_SHEET_INPUT_FILE_1), "rule=270-180-315-45-90");

-       errorTest("quit", Input.getFile(TASK_SHEET_INPUT_FILE_1), "rule=270-90-9999999999999999999999999999999999999-45-90");
+       errorTest("quit", Input.getFile(TASK_SHEET_INPUT_FILE_1),
+           "rule=270-90-9999999999999999999999999999999999999-45-90");

        errorTest("quit", Input.getFile(TASK_SHEET_INPUT_FILE_1), "Rule=90-315-45-90-270");
        errorTest("quit", Input.getFile(TASK_SHEET_INPUT_FILE_1), "ruLe=90-315-45-90-270");
@@ -122,7 +123,8 @@ public class InvalidCommandLineArgumentsTest extends LangtonSubtest {
    }

    /**
-    * Asserts that the tested class prints an error message if a non-existent file is provided as command line argument.
+    * Asserts that the tested class prints an error message if a non-existent file is provided as command line
+    * argument.
     */
    @Test
    public void noSuchFileTest() {
@@ -136,7 +138,8 @@ public class InvalidCommandLineArgumentsTest extends LangtonSubtest {
        errorTest("quit", Input.getFile(TASK_SHEET_INPUT_FILE_1), Input.getFile(TASK_SHEET_INPUT_FILE_1), "speedup=1");
        errorTest("quit", Input.getFile(TASK_SHEET_INPUT_FILE_1), Input.getFile(TASK_SHEET_INPUT_FILE_1),
            "rule=45-45-45-45-45", "speedup=1");
-       errorTest("quit", Input.getFile(TASK_SHEET_INPUT_FILE_1), "speedup=1", "rule=45-45-45-45-45", "rule=45-45-45-45-45");
+       errorTest("quit", Input.getFile(TASK_SHEET_INPUT_FILE_1), "speedup=1", "rule=45-45-45-45-45",
+           "rule=45-45-45-45-45");
        errorTest("quit", Input.getFile(TASK_SHEET_INPUT_FILE_1), "rule=45-45-45-45-45", "speedup=1",
            "rule=45-90-270-315-90");
        errorTest("quit", Input.getFile(TASK_SHEET_INPUT_FILE_1), "speedup=1", "rule=45-45-45-45-45", "speedup=1");
```

Edit: Have you manually set the tab size to something smaller than 4?

**Comment by RomanLangrehr** [comment]
Ah - that's it. I use tab width 2.

**Comment by pcworld** [comment]
> Removed the (not yet) existing Test classes MoveTest and PrintTest

They have been merged into ant-development

**Comment by RomanLangrehr** [comment]
Allright, i'll add them again...

**Comment by pcworld** [comment]
Okay, nothing more to complain from my side. [`merge --squash`](http://stackoverflow.com/a/5309051/1543768) into ant-development?

**Comment by jGleitz** [comment]
@pcworld Why can't I just merge this normally?

**Comment by pcworld** [comment]
feel free to
(I have a fetish for clean git repositories, but that's my problem ;))

**Comment by jGleitz** [comment]
> I have a fetish for clean git repositories

And that's to your credit! Alright, @RomanLangrehr, would you?

**Comment by RomanLangrehr** [comment]
I have no idea how to do this "cleanly merge"...

**Comment by jGleitz** [comment]
In Eclipse with EGit, do the following:

Make sure you're in your local `ant-development`. Rightklick on your repository and hit Reset. Select _Hard Reset_ and choose **my** `ant-development`. You have my branch state now.
Then rightclick again and select Merge. Choose **your remote** `ant-development` branch and select the _Squash_ option. You should now have the changes of this pull request squashed in your local `ant-development`.
Push your local `ant-development` to your remote `ant-development`. You'll likely have to _force_ it.

**Comment by kelunik** [comment]
You should not have to `git reset --hard` anything if you're just merging one branch into another.
`git push --force` is another thing you usually don't want to do. I'd just merge this _as is_ or using `--squash` it doesn't really matter. But `--squash` seems actually pretty nice and something I should remember.

**Comment by jGleitz** [comment]
@kelunik Hard reset could be a checkout, too, I guess… Furthermore, I don't see how to do this _without_ force pushing. Because we want to get rid of the old commits, that's what's this all about. And that's impossible without forcing the push.
You could open a new branch and a new pull request, then you could avoid both. But what's the point?

But correct me if I'm wrong, I'd like to learn!

**Comment by pcworld** [comment]
> I don't see how to do this without force pushing

Usually, you would do your changes on a new branch and not on the branch you want to merge to as Roman did. Assume you made your commits on a branch `mergeme`:

```
git checkout ant-development
git merge --squash mergeme
git branch -d mergeme
git push origin :mergeme # if you want to delete the branch on your remote repo
git push jgleitz # if jgleitz is a remote of this repo
```

Actually, even in Roman's situation you could create a new branch from the current state of ant-development and then reset ant-development to this remote repo (if you're in ant-development, `git checkout -b mergeme`, then `git checkout ant-development && git reset --hard jgleitz/ant-development` (not sure if `--hard` is needed), then continue with above steps).

**Comment by jGleitz** [comment]
Yep, that's another option. (But once again I don't see what's so bad about a hard reset). Lazy people reuse branches ;)

**Comment by kelunik** [comment]
There's nothing bad about `git reset --hard`. It just resets your current working directory to the latest commit. So it's only needed if you have uncommited work that you want to loose.

`git checkout` doesn't do any reset, would be very easy to loose work if it would.

There's no real gain in reusing branches for that. You can reuse a branch if you want to your commits as is in your history, but if you want to do multiple commits for a specific feature and have it later as a single commit, you'd be better with creating a new branch.

If I got that right, `--squash` creates a new commit that contains all your previous commits in one commit. That's a single new commit to your `ant-development` branch here, so there's no need to `push --force`. Force pushing is really bad, because you would loose any commit anybody else did that's not in your local history.

**Pull request closed without merging**
