### PR TITLE
Improvement of Runs

### LINKED ISSUE #101: LineRun/ExportRun remove trailing newlines
I just noticed we made the same mistake as it is found in FileInputHelper.
`mergedOutputBuilder.toString().split("\n")` removes trailing empty lines from user output, and returns one empty line even if no call to Terminal.printLine has been made. The former might be possible to fix by passing a `-1` parameter to split.

### PR DESCRIPTION
**Pull request by jGleitz**
- Fixes #101 
- more detailed error messages
- more flexible code
- reduced redundancy

### CODE REVIEW

**Comment by pcworld** [comment]
ExportRun now throws an ArrayIndexOutOfBoundsException if no calls to Terminal.printLine() were made. Surprisingly, this error also happens when Terminal.printLine is called one time with an empty line (`Terminal.printLine("")`), but not if it is called twice with empty lines.

Otherwise lgtm, but didn't do a detailed review.

**Comment by jGleitz** [comment]
> ExportRun now throws an ArrayIndexOutOfBoundsException if no calls to Terminal.printLine() were made.

Fixed in    c490e45

**Comment by pcworld** [comment]
Are you sure there is no bug elsewhere? Because when I made one `Terminal.printLine("")` call, `outputLines` had length 0.

**Comment by jGleitz** [comment]
I am aware of the other bug. The following:

``` java
Scanner scanner = new Scanner("\n");
scanner.useDelimiter("\n");
boolean result = scanner.hasNext();
```

`result` is `false`. Which I did not expect.

**Comment by pcworld** [comment]
Stupid methods that try to be smart :) (Scanner, split, …)

**Comment by jGleitz** [comment]
> Stupid methods that try to be smart :) (Scanner, split, …)

The all have their internal logic, but Murphy's law guarantees they always behave differently from what you expect. 
What really bugs my about `Scanner` is this:

``` java
        Scanner scanner = new Scanner("\n");
        scanner.useDelimiter("\n");
        while (scanner.hasNext()) {
            System.out.println("|" + scanner.next() + "|");
        }
```

output:

```
```

``` java
        Scanner scanner = new Scanner("\n\n");
        scanner.useDelimiter("\n");
        while (scanner.hasNext()) {
            System.out.println("|" + scanner.next() + "|");
        }
```

output:

```
||
```

``` java
        Scanner scanner = new Scanner("Hallo\nWelt\n");
        scanner.useDelimiter("\n");
        while (scanner.hasNext()) {
            System.out.println("|" + scanner.next() + "|");
        }
```

output:

```
|Hallo|
|Welt|
```

``` java
        Scanner scanner = new Scanner("Hallo\nWelt\n\n");
        scanner.useDelimiter("\n");
        while (scanner.hasNext()) {
            System.out.println("|" + scanner.next() + "|");
        }
```

output:

```
|Hallo|
|Welt|
||
```

**FUUUUUUU!**

**Comment by pcworld** [comment]
For file reading it does make sense, since some software/people terminate their files with just `EOF` and some with `\nEOF` (and probably some with  `\r\nEOF` or `\rEOF`).

**Comment by jGleitz** [comment]
Fixed it with 474deeb.

The solution is surprisingly simple: Just add `\n` at the start.

**Comment by pcworld** [comment]
I haven't found the time to test this last commit, but I guess we can merge this so this makes it in before the deadline of final1 and stuff

**Pull request merged**
