### PR TITLE
major framework refactor – please test!

### PR DESCRIPTION
**Pull request by jGleitz**
**Please test this pull request!**

The terminal class is now mocked by a class compiled at runtime. The rewritten `TestClassLoader` now loads all classes referenced by a tested class. Inner classes of `TestObject` have been moved to their own files (in new introduced package `test.framework`)
- contains fix for #31
- implements #15
- introduces regression:
  - task 5 sheet test stopped working (death loop)
  - major performance hit because of runtime compiling

### CODE REVIEW

**Comment by jGleitz** [comment]
This pull request introduces a major performance hit (overhead for first test method). Therfore, testing (see [instructions](https://help.github.com/articles/checking-out-pull-requests-locally/)) would be appreciated! Please report on how bad you feel it is.

**Comment by jGleitz** [comment]
As @RomanLan reported, this merge will break everything on environments where `ToolProvider.getSystemJavaCompiler()` cannot be used to retrieve a Compiler (returns `null`). Unfortunately, that seems to be the case for most Windows Eclipse installations.

**Comment by jGleitz** [comment]
@RomanLan : Could you give the new Commits a try? dd3d81b _could_ solve the issue.

**Comment by RomanLangrehr** [comment]
@jGleitz I'm sorry, but it didn't solve the problem. All tests crash with an ExceptionInInitialzerError, caused by an test.framework.FrameworkException: Your system does not provide a Java Compiler. It's Windows, but we can't find a JDK! [...]

**Comment by jGleitz** [comment]
:( . @RomanLan as you're the only tester with Windows in the moment, I hope I may ask further questions:
- Do you have a JDK installed?
- Do you have a folder `C:\Program Files\Java`?
- If yes, what are the contents (first level subfolders) of this folder?

**Comment by RomanLangrehr** [comment]
@jGleitz I have installed jdk1.7 and jre1.8, both are in the folder C:\Program Files\Java and here are the subfolders:
image
image

**Comment by jGleitz** [comment]
Oh no, did a typo and searched for `jdk-1.` instead of `jdk1.`. Fixed that in 7377b73. @RomanLan could you please give it another try?

**Comment by RomanLangrehr** [comment]
@jGleitz The test prints nearly hundred warnings and nearly hundred times "null" on the console, but it works fine (everything is green).

By the way: it needs ~3.5 seconds

**Comment by jGleitz** [comment]
@RomanLan : Now that's good news! Very glad to hear it. Even though ~3.5s are more than I hoped it would take. Would you say that's a big inconvenience? 
Printing null was an old test of mine. Totally forgot to remove it. Fixed in f9f0fd1. 
The warnings, meanwhile, are unexpected. Could you please share the warnings that are printed?

**Comment by RomanLangrehr** [comment]
@jGleitz Here are the warings:

`warning: C:\Program Files\Java\jre1.8.0_31\lib\rt.jar(java/util/LinkedList.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: C:\Program Files\Java\jre1.8.0_31\lib\rt.jar(java/util/List.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: C:\Program Files\Java\jre1.8.0_31\lib\rt.jar(java/util/Arrays.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: C:\Program Files\Java\jre1.8.0_31\lib\rt.jar(java/util/concurrent/BlockingQueue.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: C:\Program Files\Java\jre1.8.0_31\lib\rt.jar(java/util/concurrent/LinkedBlockingQueue.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: C:\Program Files\Java\jre1.8.0_31\lib\rt.jar(java/lang/Object.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: C:\Program Files\Java\jre1.8.0_31\lib\rt.jar(java/lang/String.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: C:\Program Files\Java\jre1.8.0_31\lib\rt.jar(java/lang/AutoCloseable.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: C:\Program Files\Java\jre1.8.0_31\lib\rt.jar(java/util/Collection.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: C:\Program Files\Java\jre1.8.0_31\lib\rt.jar(java/util/AbstractSequentialList.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: C:\Program Files\Java\jre1.8.0_31\lib\rt.jar(java/util/AbstractList.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: C:\Program Files\Java\jre1.8.0_31\lib\rt.jar(java/util/AbstractCollection.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: C:\Program Files\Java\jre1.8.0_31\lib\rt.jar(java/lang/Iterable.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: C:\Program Files\Java\jre1.8.0_31\lib\rt.jar(java/util/AbstractQueue.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: C:\Program Files\Java\jre1.8.0_31\lib\rt.jar(java/util/Queue.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: C:\Program Files\Java\jre1.8.0_31\lib\rt.jar(java/lang/InterruptedException.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: C:\Program Files\Java\jre1.8.0_31\lib\rt.jar(java/lang/Exception.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: C:\Program Files\Java\jre1.8.0_31\lib\rt.jar(java/lang/Throwable.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: C:\Program Files\Java\jre1.8.0_31\lib\rt.jar(java/lang/RuntimeException.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: C:\Program Files\Java\jre1.8.0_31\lib\rt.jar(java/lang/Error.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
20 warnings
`

And i don't have a problem with waiting ~3.5 seconds for the test to finish,so think you don't have to worry about that.

**Comment by jGleitz** [comment]
@RomanLan: You're running Java 8 on the Programming Tasks – naughty boy! :D
I hope I muted the warnings with the last commit.

**Comment by jGleitz** [comment]
As I don't see any fatal errors with this request anymore, I'm going to merge. Please report further errors in issues!

**Pull request merged**
