### PR TITLE
Added + prefix for rule and speedup

### LINKED ISSUE #143: Assert that integers prefixed with a + are not allowed
Integer.parseInt accepts a `+` prefix for nonnegative numbers. Some implementations might accept program arguments like `speedup=+3 rule=+270-+90-+315-+45-+90`, and anywhere else where integers are parsed (CLI commands).

### PR DESCRIPTION
**Pull request by RomanLangrehr**
Fixes #143

### CODE REVIEW

**Comment by jGleitz** [comment]
> Fixes #143

Not quite, we still don't have a test for the input files, have we?

**Comment by jGleitz** [comment]
Apart from that, lgtm.

**Comment by RomanLangrehr** [comment]
> Not quite, we still don't have a test for the input files, have we?

I dont think that this is necassary, as a input file like:

0+10
0a0

is rather a input field with invalid characters and inalid row lengths. And I can't imagine a implementation interpreting this as 

010
0a0

**Comment by jGleitz** [comment]
> And I can't imagine

Broaden your imagination :D

I'd like to have a little test for it. Just one. This pull would be a nice play to do it, would you?

**Comment by RomanLangrehr** [comment]
Ok, done...

**Comment by jGleitz** [comment]
:+1: ! If you'd merge with `ant-development`, we can merge this pull request.

**Comment by RomanLangrehr** [comment]
I'm trying to merge, but my git repository is broken again, due to a reset, so it may take a while...

**Comment by pcworld** [comment]
lgtm

**Pull request merged**
