### PR TITLE
Added empty line tests

### LINKED ISSUE #133: Add empty line tests
We should add a test for empty lines in the input file to the invalid input file tests.

### PR DESCRIPTION
**Pull request by RomanLangrehr**
Fixes #133

### CODE REVIEW

**Comment by jGleitz** [comment]
I'm missing:
- Just one empty line
- Just multiple empty lines

**Comment by RomanLangrehr** [comment]
You're absolutly right. I'll add them soon...

**Comment by pcworld** [comment]
completely empty file (i.e. 0 bytes) should be added too

**Comment by jGleitz** [comment]
Yup

**Comment by RomanLangrehr** [comment]
I think an empty file (0 bytes) and and a file with one empty line are equal files ?!

**Comment by pcworld** [comment]
Depends on your definition of lines: https://en.wikipedia.org/wiki/Newline
Edit: In my opinion, a line is always _terminated_ with a LF. The other interpretation is that lines are _separated_ by LFs.

**Comment by jGleitz** [comment]
> Depends on your definition of lines

Not in Java. Java uses the _termination_ philosphy. Therfore, `{""}` gets `"\n"`, but `{}` will be a real 0 byte file.

**Comment by RomanLangrehr** [comment]
Ok. I added the tests...

**Comment by jGleitz** [comment]
lgtm

**Comment by pcworld** [comment]
+1

**Comment by pcworld** [comment]
Wait, this is not entirely valid (must be fixed for some other already merged "no ant tests" as well):
https://ilias.studium.kit.edu/ilias.php?ref_id=413546&cmdClass=ilobjforumgui&thr_pk=53364&pos_pk=196345&offset=0&cmd=viewThread&cmdNode=ed:5v&baseClass=ilRepositoryGUI#196345

> Sie können eine Eingabedatei ohne Ameise als semantischen Fehler werten, oder das Programm ohne Ausgabe terminieren, so wie es die move- und escape-Befehle tun.

**Comment by RomanLangrehr** [comment]
> Wait, this is not entirely valid (must be fixed for some other already merged "no ant tests" as well):

Okay...
But I have no idea how to test this...

**Comment by jGleitz** [comment]
> But I have no idea how to test this...

See #144

**Comment by jGleitz** [comment]
Wait, why is this an issue here? `""` does not form a valid board and is therefore invalid! I think this issue only applies to the other tests.

**Comment by pcworld** [comment]
> Wait, why is this an issue here? "" does not form a valid board and is therefore invalid!

You might be right. I just looked at the sheet again and it does not seem to make an unambiguous statement on whether a field must have at least one cell.

**Comment by jGleitz** [comment]
From my point of view, we can merge this.

**Pull request merged**
