### PR TITLE
Merge into master

### PR DESCRIPTION
**Pull request by jGleitz**
I don't want to merge quite now, but rather use this to discuss what's missing to consider the tests stable.

### CODE REVIEW

**Comment by pcworld** [comment]
#164 should be "fixed"

**Comment by jGleitz** [comment]
True. I'm going to post an ILIAS question about it.

I'm thinking whether we should disable the tests concening #164 and #165
until we have an official statement.

Am 28.03.2015 um 14:28 schrieb pcworld:

**Comment by pcworld** [comment]
> I'm thinking whether we should disable the tests concening #164 and #165
> until we have an official statement.

If we merge into master without having come to a good solution for these issues, I'd agree with disabling them.
Edit: Leaving them on will confuse users or even lead users to breaking their implementations if they trust our tests.

**Comment by jGleitz** [comment]
> Leaving them on will confuse users or even lead users to breaking their implementations if they trust our tests.

That's exactly my point.

**Comment by pcworld** [comment]
IMO, after we merge #177 and #178, we can merge to master and from then on commit directly to master.

**Comment by jGleitz** [comment]
I merged #175, #176, and #178 to have them included in this pull, even though not all questions asked there were solved. This should not stop the discussion there, but it's Sunday morning and I really want people to have these tests available in `master`. Therefore merging.

**Pull request merged**
