### PR TITLE
Better sorting of ant-subtests

### PR DESCRIPTION
**Pull request by jGleitz**
Unlike test methods in a test class, the test classes defined for a suite are run strictly in the order they are declared.

Therefore I'd like to establish this new sorting, which makes much more sense IMHO. It runs tests that test preconditions of other tests first.

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
Thats a good idea. But, i would move all "illegal" tests to the end, because the "correct" tests work without them and it is more important, that a program works correctly (at least on a basic level), than to handle all exceptions correctly.

**Comment by pcworld** [comment]
> But, i would move all "illegal" tests to the end, because the "correct" tests work without them and it is more important, that a program works correctly (at least on a basic level), than to handle all exceptions correctly.

+1

**Comment by jGleitz** [comment]
You have a point.

I moved the invalid tests so they run _after_ the basic tests, but _before_ the complete scenario tests. (I think we're gonna have at least one more class which will check that all commands work as expected if combined. In the moment, we only try them separately (which is a good thing, I think)).

**Comment by pcworld** [comment]
lgtm. Many tests currently depend on other tests/commands, so there's no perfect order, so I think we're good to go with the latest commit here.

**Comment by RomanLangrehr** [comment]
I think that is the perfecct solution.

**Comment by jGleitz** [comment]
> Many tests currently depend on other tests/commands.

Yeah, that's a shame, but we can't prevent it.

**Pull request merged**
