### PR TITLE
Testing for different relations

### PR DESCRIPTION
**Pull request by jGleitz**
- reworked the way we test for all relation types, as this is unfortunately not trivial due to different arguments.
- implements #67
- implements #43

### CODE REVIEW

**Comment by pcworld** [comment]
#65?

**Comment by jGleitz** [comment]
Bullshit. #67

**Comment by pcworld** [comment]
lgtm. Did you actually test that these commands create the input files we think they do? (So as not to make the same mistake I did earlier.)

**Comment by jGleitz** [comment]
I did not test every single one, but looked at three of them. The were formed as I expected them to be.

**Comment by pcworld** [comment]
I guess this is ok to merge. I looked in the debugger to see if it creates at least some valid (pseudo) circles, and as that was given, merging this hopefully shouldn't make anything worse even if this contains bugs.

**Pull request merged**
