### PR TITLE
Improved way to call multiLineTest

### PR DESCRIPTION
**Pull request by jGleitz**
I added a new nested class `InteractiveConsoleTest.Run` as well as a new overload for `InteractiveConsoleTest.multiLineTest`. As explained in the docs, the new syntax would allow calls like this:

``` java
Run[] runs = new Run[] {
          new Run("command1", is("Success!")),
          new Run("command2", is("Success!")),
          new Run("command3", is("Success!")),
          new Run("command4", is("")),
          new Run("command5", startsWith("Error,"))
 };
multiLineTest(runs, args0);
```

This should be an acceptable solution for some of the issues discussed in #42.

### CODE REVIEW

**Comment by pcworld** [comment]
lgtm. Can Run match multiple lines of output per command?

**Comment by jGleitz** [comment]
[IGTM](http://acronymsandslang.com/IGTM-meaning.html)? As described in #74 the current framework limits matchers to match one call to `Terminal.printLine`. So yes, it can match mutliple lines of output, but not multiple calls to `Terminal.printLine`. 

This can only by fixed once #74 is.

**Comment by pcworld** [comment]
LGTM = looks good to me. (It's a phrase I've commonly seen on the Chromium Gerrit when people approve for merging.)

**Comment by jGleitz** [comment]
I'm closing this. I'm going implement a solution for #74 which will allow this syntax, too.

**Pull request closed without merging**
