### PR TITLE
Added some more invalid syntax data file tests

### PR DESCRIPTION
**Pull request by RomanLangrehr**

### CODE REVIEW

**Comment by jGleitz** [comment]
I have not checked it throughout, but I get the feeling some of the test you added are already asserted in other test methods. We have to make sure that our collaborations does not end in testing the same thing multiple times.
Are you sure everything you added is "new"?

**Comment by RomanLangrehr** [comment]
Yes, actually 4 test cases were already tested in invalidArguementCountTest() and invalidSymbolTest(). I removed them and  I'll make a new Pull Request right now,

**Comment by jGleitz** [comment]
Don't make a new one. If you have changes for a pull request, just push them into the pull request's source branch. They will appear automatically in the pull request.

**Comment by RomanLangrehr** [comment]
Ok. I think I actually pushed them here by mistake ;)

**Comment by RomanLangrehr** [comment]
Oh, no, wait a moment...

**Comment by RomanLangrehr** [comment]
Now I really remove them...

**Comment by jGleitz** [comment]
Alright. Merging then.

**Pull request merged**
