### PR TITLE
Added Test for 06A

### PR DESCRIPTION
**Pull request by RomanLangrehr**
Added a test for Sheet 06 Task A. The test is based on the test for Sheet 05 Task C and isn't complete yet.
In particular the info command is tested at all yet.

### CODE REVIEW

**Comment by jGleitz** [comment]
Would you mind adapting the "new" syntax? Especially:
- writing multi line commands and expected results in an String Array:
  <pre>
  commands = new String[] {
      "command1",
      "command2",
      "etc."
  };
  expectedResults = new String[] {
      "result1",
      "result2",
      "etc."
  };
  multiLineTest(commands, expectedResults, args);
  </pre>
- Defining files as an String array, like: 
  
  <pre>
  file = new String[] {
      "line1",
      "line2",
      "etc"
  };
  ...
  oneLineTest(commands, "", getFile(file));
  </pre>
  
  you could take the `getFile(String[] lines)` method from Task C, of course.
- stating non-trivial results and commands before the call to the method of `InteractiveConsoleTest`. We have the protected fields `command`, `commands`, `expectedResult`, `expectedResults`, etc. in `InteractiveConsoleTest` for that. With non-trivial I mean all commands that are neither `""` nor `"quit"` and all results that are not `""`, `startsWith("Error,")` or `not(startsWith("Error,"))`. A "nice" call would look like the first example.

Honestly, I find it quite hard to understand what you test actually does, in the moment. I would appreciate if it was written in the new syntax, as I think it's better readable.
You might look in Task C for reference. If you disagree in the readability of the syntax, we can discuss it, of course.

**Comment by MartinLoeper** [comment]
Joshua, could you paste some of your code-style-guidelines into a new wiki
page called "Code Style" or similar?
They would be easier to find for future contributions.
Am 31.01.2015 15:28 schrieb "Joshua Gleitze" notifications@github.com:

**Comment by jGleitz** [comment]
@MartinLoeper You are absolutely right. I'll do that right away.

**Comment by RomanLangrehr** [comment]
The methode getFile(String[] lines) from Task C is not usable, because it is not public.
Why isn't this methode in the InteractiveConsoleTest class anyway?

**Comment by jGleitz** [comment]
@RomanLan You are right, it should be public. I moved it to the new `Input` class as its only remotely connected to testing an interactive console.

**Comment by jGleitz** [comment]
I started writing a Style guideline at https://github.com/jGleitz/JUnit-KIT/wiki/Style-guidelines. I will extend it at a later point.
Please feel free to discuss the guidelines (or ask questions, I really set up this wiki page in a hurry). I made them up all by myself, there might sure be some things to improve.

**Pull request closed without merging**
