### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by jGleitz**
- Removed and excluded `.classpath`
- Removed `javadoc.css` (now only in `gh-pages`)

### CODE REVIEW

**Comment by pcworld** [comment]
lgtm

**Comment by jGleitz** [comment]
Please note that this will likely break your Eclipse project, as `.classpath` got removed. But as `.classpath` is excluded through `.gitignore`, you might just download it from `master` and add it again.

**Comment by pcworld** [comment]
Or just readd JUnit to the project's build path settings.

**Comment by jGleitz** [comment]
In my case, Eclipse got totally confused with `src` and `bin`.

**Comment by pcworld** [comment]
I did a project cleanup too, not sure if this was necessary.

**Pull request merged**
