### PR TITLE
Added leading zeros test

### LINKED ISSUE #68: Test 0 prefix for IDs
IDs in the form of `0000105` have to be treated as if the leading zeros where not existent. Therefore they have to be 
- accepted
- Treated like their counterparts without leading zeros. Therefore `0000105` has to treated as if it was `105`

There will not be an official test for this behaviour in the `recommend` command, which seems to imply that it won't be tested for the input files, too (But this is my interpretation!).
Anyone implementing this could consider opening a `OptinalRecommendationTest` that runs all mandatory tests and some more that are not required but “nice to have”.

### PR DESCRIPTION
**Pull request by RomanLangrehr**
fixes #68 
I hope I used the new Formatter correctly...

### CODE REVIEW

**Comment by jGleitz** [comment]
I think we should add a test for an invalid input file that uses e.g. 00000105 and 105 as an ID for two different products.

**Comment by RomanLangrehr** [comment]
Ok, thats a good idea. I'll create one...

**Comment by jGleitz** [comment]
Unfortunately, merging #65 (which was long overdue) broke this pull. @pcworld split `testAgainstTaskSheet` and sorted some tests that asserted several aspects at once in their corresponding classes.

Make sure to match the “new” order when merging!

**Comment by RomanLangrehr** [comment]
I'll make a new Pull Request soon, as my repository is broken now :(

**Comment by RomanLangrehr** [comment]
Replaced by #94

**Pull request closed without merging**
