### PR TITLE
final2: direction of northwest can be "SW"

### PR DESCRIPTION
**Pull request by pcworld**
"Fixes" #182.
I know this is quite stupid, but this approximates our tests more to the hypothetical official tests.
Feel free to comment if you are against merging, it would be really understandable.

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
I don't think it's a good idea to merge this.
It's definitely more like the official test, BUT:
If somebody really prints SW instead of NW in the direction command, things get really hard to debug. So in my opinion, it's best to not allow this. (Especially as we use the direction command to make sure an ant rotated correctly...).
To put it in a nutshell: Things will get really unnecessarily confusing with this change! Avoid it.

**Comment by jGleitz** [comment]
This is stupid as f**k. I wanted to include it like @pcworld proposed but @RomanLangrehr actually has a point. The same argumentation again: If somebody changes his implementation because of us, this won't do no harm at all.

Nevertheless, it would likely make sense to document this decision anywhere.

**Comment by pcworld** [comment]
> Nevertheless, it would likely make sense to document this decision anywhere.

We could add comments after all `is("NW")` lines, referring to #182 or the ILIAS link to the official statement.

**Comment by jGleitz** [comment]
I'd prefer the ILIAS link. Would you do that?

**Comment by pcworld** [comment]
My only issue with ILIAS links is that they are longer than 120 characters and will probably confuse the formatter. I'll give it a try nonetheless

**Comment by jGleitz** [comment]
Use a shortener!

**Comment by pcworld** [comment]
> Use a shortener

I thought about that too, but IMO that's even worse than including a GitHub link. ("link shorteners" hide the real location etc.)

**Comment by pcworld** [comment]
See #186. I really liked the `anyOf` matcher though ;P

**Pull request closed without merging**
