### PR TITLE
final1: Remove incomplete failures

### PR DESCRIPTION
**Pull request by pcworld**
And fix formatting.

I feel like the existing tests are sufficient and not incomplete anymore.
The only one I'm not too sure about is ValidNodesCommandTest since it doesn't test against many cases, on the other hand I can't think of any more special cases.

### CODE REVIEW

**Comment by jGleitz** [comment]
I'm in the process of reviewing what we have so far.
Removing the `incomplete` fails could go hand in hand with merging into `master`.

**Comment by jGleitz** [comment]
@pcworld would you upload a merged one? As soon as possible, you may merge this pull request. I'll create a PR to merge into master afterwards.

**Comment by pcworld** [comment]
I'll do.

> I'll create a PR to merge into master afterwards.

This will then hopefully be PR #100 :)

**Comment by pcworld** [comment]
Done.

**Comment by jGleitz** [comment]
> This will then hopefully be PR #100

It is! This satisfies me more than it should ;)

**Pull request closed without merging**
