### PR TITLE
Common Eclipse Formatter & Cleanup configuration

### LINKED ISSUE #56: Formatter file
What formatter file should we use?
Currently, everyone uses their own or none it seems.

### PR DESCRIPTION
**Pull request by jGleitz**
I added the configuration xml files for Eclipse Formatter and Cleanup. They realize how I think code should look like – but that's open for discussion, of course.

I would like to have everyone importing the files and apply them before pushing commits.

This fixes #56

### CODE REVIEW

**Comment by pcworld** [comment]
Where's the configuration files in this commit?

**Comment by pcworld** [comment]
Also, I'm not sure if ordering methods alphabetically really is the way to go. (E.g. in InvalidInputFileTest the circles methods are split now.)

**Comment by jGleitz** [comment]
@pcworld: I forgot to actually add the files. They are there now.

**Comment by jGleitz** [comment]
@pcworld: I see your point regarding the sort ordering. I removed it from the cleanup config.

**Comment by pcworld** [comment]
I find using `final` for all local variables a bit overkill.

**Comment by jGleitz** [comment]
@pcworld: To manually write, yes. But to have it inserted by a program: Why not?

**Comment by pcworld** [comment]
You could also just use a code analysis tool to find reassignments of local variables.
Automatically adding `final` to variables that are currently not being reassigned, but not adding `final` to variables that are currently being reassigned, is rather pointless.
Because if you want to do a reassignment, you'll just remove the `final` keyword, so automatically adding it to all variables doesn't do anything after all other than adding clutter.
So where local `final` variables do make sense should be decided by humans, and should probably be used sparingly as not to have the same issue as the one with the automatic "cleanup" as explained above.

**Comment by jGleitz** [comment]
In my understanding, adding `final` is not to avoid reassignments, but rather for optimization.

**Comment by jGleitz** [comment]
But, on the other hand, it _does_ add clutter. And who cares for the speed of tests anyway?

**Comment by pcworld** [comment]
> In my understanding, adding final is not to avoid reassignments, but rather for optimization.

I'd guess the compiler is smart enough to see when local variables are not being reassigned.
(No source for that though.)

> But, on the other hand, it does add clutter. And who cares for the speed of tests anyway?

spot-on.

**Comment by jGleitz** [comment]
> I'd guess the compiler is smart enough to see when local variables are not being reassigned.
> (No source for that though.)

Absolutely. I would expect this from any decent compiler.

**Comment by jGleitz** [comment]
Shall we merge?

**Comment by pcworld** [comment]
Please wait for #60. I don't want to do a new rebase

**Comment by pcworld** [comment]
When I format RecommendationSubtest.java, I get this diff (cleanup says there's nothing to change):

``` diff
diff --git a/src/final1/subtests/RecommendationSubtest.java b/src/final1/subtests/RecommendationSubtest.java
index 46c5c24..47ac776 100644
--- a/src/final1/subtests/RecommendationSubtest.java
+++ b/src/final1/subtests/RecommendationSubtest.java
@@ -10,7 +10,7 @@ import test.TestObject;
 /**
  * Base class for implementing subtest for the programming lecture's first final task. Contains some convenience methods
  * and fields.
- *
+ * 
  * @author Joshua Gleitze
  * @author Martin Loeper
  * @version 1.1
@@ -82,11 +82,11 @@ public abstract class RecommendationSubtest extends InteractiveConsoleTest {
     };

     protected String[] ONE_LINE_INPUT_FILE1 = new String[] {
-            "B(id=1) successor-of A(id=2)"
+        "B(id=1) successor-of A(id=2)"
     };

     protected String[] ONE_LINE_INPUT_FILE2 = new String[] {
-            "A contains B(id=2)"
+        "A contains B(id=2)"
     };

     protected String[] PSEUDO_CIRCLE_INPUT_FILE1 = new String[] {
@@ -108,7 +108,7 @@ public abstract class RecommendationSubtest extends InteractiveConsoleTest {
      * <p>
      * This method is deprecated as its function is now provided by
      * {@link InteractiveConsoleTest#setExpectedSystemStatus}
-     *
+     * 
      * @param command
      *            The command to run on the console.
      * @param args0
@@ -125,7 +125,7 @@ public abstract class RecommendationSubtest extends InteractiveConsoleTest {
      * <p>
      * This method is deprecated as its function is now provided by
      * {@link InteractiveConsoleTest#setExpectedSystemStatus}
-     *
+     * 
      * @param commands
      *            The commands to run on the console
      * @param args0
@@ -141,7 +141,7 @@ public abstract class RecommendationSubtest extends InteractiveConsoleTest {

     /*
      * (non-Javadoc)
-     *
+     * 
      * @see test.InteractiveConsoleTest#consoleMessage(java.lang.String[], java.lang.String[])
      */
     @Override
```

So I'm assuming there's something wrong.

**Comment by jGleitz** [comment]
What exactly do you think is wrong?

**Comment by pcworld** [comment]
Well, I assume that in your commit you already formatted all files according to the formatter you've shared, but in my case it still changes some spacings.

**Comment by jGleitz** [comment]
You're right. 
I can't tell what's the "right" version on this case. But what is remarkable is that the formatter _added_ a space in the Javadoc, while the cleanup tool is set to _remove_ tailing

**Comment by jGleitz** [comment]
*whitespace. Did you run the formatter solely or did you run the cleanup tool?

**Comment by pcworld** [comment]
First formatter then cleanup tool. Cleanup tool said there were no resulting changes in source code.

**Comment by jGleitz** [comment]
``` diff
diff ~/Dokumente/Uni/Bachelor\ Informatik/WS\ 1/Programmieren/Joshua.privat/JUnit-KIT/src/final1/subtests/RecommendationSubtest.java ~/Ablage/RecommendationSubtest.java 
85c85
<         "B(id=1) successor-of A(id=2)"
---
>             "B(id=1) successor-of A(id=2)"
89c89
<         "A contains B(id=2)"
---
>             "A contains B(id=2)"
144c144
<      * 
---
>      *
150,152c150,151
<         result +=
<                 "We ran a session on your interactive console" + Input.fileMessage(commandLineArguments[0])
<                         + " running the commands \n\n" + joinOnePerLine(commands) + "\n\n but got unexpected output:\n";
---
>         result += "We ran a session on your interactive console" + Input.fileMessage(commandLineArguments[0])
>                 + " running the commands \n\n" + joinOnePerLine(commands) + "\n\n but got unexpected output:\n";
```

This looks quite similar to me. Either the Cleanup tool missed this file out the last time I used it, or it got overwritten by another commit, or the tools are a bit unreliable.
Anyway as we both get the same results, I'd say we can savely start using the new configurations.

P.S.: How do you do that git-like diff? Mine doesn't know the option `--git`.

**Comment by pcworld** [comment]
> Anyway as we both get the same results, I'd say we can savely start using the new configurations.

Okay, fine.

> P.S.: How do you do that git-like diff? Mine doesn't know the option --git.

`git diff` ;)
Edit: And when you're not using git, you can use the `-u` option on diff to get unified diff format.

**Comment by jGleitz** [comment]
Thanks :)

The issue we had here is a reproducible bug, see #63

**Pull request merged**
