### PR TITLE
Added first test for invalid recommend terms

### LINKED ISSUE #48: Test invalid ids in recommend terms
We should test invalid product ids (chars in ids or ids too large for integers) in recommend terms.

### PR DESCRIPTION
**Pull request by RomanLangrehr**
Create some tests for invalid recommend terms.
They are not complete yet!
Fixes #48

### CODE REVIEW

**Comment by jGleitz** [comment]
> weather

I don't know whether the weather is sunny or not, but I assume you meant 'whether' ;)

I like the 'asserts that' wording better, but that's just a suggestion. You may want to fix the typo, though.

**Comment by RomanLangrehr** [comment]
Ok ;)
Is done.

**Comment by RomanLangrehr** [comment]
I'm always doing this typo.....:
image

**Comment by jGleitz** [comment]
Oh. :)

**Pull request merged**
