### PR TITLE
Merge into master

### PR DESCRIPTION
**Pull request by jGleitz**
The tests for final task 1 can be considered stable enough to merge them. Further development for final task 1 may happen by merge requests into `master` directly.

### CODE REVIEW

**Comment by pcworld** [comment]
Now GitHub is optimistic!
selection_210

**Comment by jGleitz** [comment]
Docs are already updated for this state in `gh-pages`. From my point of view, this can be merged. Anybody wanting to may take the honour of merging PR #100 :D

**Comment by jGleitz** [comment]
> Now GitHub is optimistic!

Obviously, it can't count that high :D

**Comment by pcworld** [comment]
I kept thinking if I should press return, but then I pressed it and bäämm.

**Comment by pcworld** [comment]
Crap, I forgot a Portal 2 "testing" reference :P

**Pull request merged**
